// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: frontier.proto

#include "frontier.pb.h"
#include "frontier.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace frontier {

static const char* Frontier_method_names[] = {
  "/frontier.Frontier/GetURLs",
  "/frontier.Frontier/SubmitURLs",
};

std::unique_ptr< Frontier::Stub> Frontier::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Frontier::Stub> stub(new Frontier::Stub(channel, options));
  return stub;
}

Frontier::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetURLs_(Frontier_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SubmitURLs_(Frontier_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Frontier::Stub::GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::frontier::URLResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frontier::URLRequest, ::frontier::URLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetURLs_, context, request, response);
}

void Frontier::Stub::async::GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frontier::URLRequest, ::frontier::URLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetURLs_, context, request, response, std::move(f));
}

void Frontier::Stub::async::GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetURLs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>* Frontier::Stub::PrepareAsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frontier::URLResponse, ::frontier::URLRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetURLs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>* Frontier::Stub::AsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetURLsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Frontier::Stub::SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::frontier::SubmitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::frontier::URLBatch, ::frontier::SubmitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SubmitURLs_, context, request, response);
}

void Frontier::Stub::async::SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::frontier::URLBatch, ::frontier::SubmitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitURLs_, context, request, response, std::move(f));
}

void Frontier::Stub::async::SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SubmitURLs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>* Frontier::Stub::PrepareAsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::frontier::SubmitResponse, ::frontier::URLBatch, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SubmitURLs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>* Frontier::Stub::AsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSubmitURLsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Frontier::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Frontier_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Frontier::Service, ::frontier::URLRequest, ::frontier::URLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Frontier::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frontier::URLRequest* req,
             ::frontier::URLResponse* resp) {
               return service->GetURLs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Frontier_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Frontier::Service, ::frontier::URLBatch, ::frontier::SubmitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Frontier::Service* service,
             ::grpc::ServerContext* ctx,
             const ::frontier::URLBatch* req,
             ::frontier::SubmitResponse* resp) {
               return service->SubmitURLs(ctx, req, resp);
             }, this)));
}

Frontier::Service::~Service() {
}

::grpc::Status Frontier::Service::GetURLs(::grpc::ServerContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Frontier::Service::SubmitURLs(::grpc::ServerContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace frontier

