// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: frontier.proto
#ifndef GRPC_frontier_2eproto__INCLUDED
#define GRPC_frontier_2eproto__INCLUDED

#include "frontier.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace frontier {

class Frontier final {
 public:
  static constexpr char const* service_full_name() {
    return "frontier.Frontier";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::frontier::URLResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>> AsyncGetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>>(AsyncGetURLsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>> PrepareAsyncGetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>>(PrepareAsyncGetURLsRaw(context, request, cq));
    }
    virtual ::grpc::Status SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::frontier::SubmitResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>> AsyncSubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>>(AsyncSubmitURLsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>> PrepareAsyncSubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>>(PrepareAsyncSubmitURLsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>* AsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frontier::URLResponse>* PrepareAsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>* AsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::frontier::SubmitResponse>* PrepareAsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::frontier::URLResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>> AsyncGetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>>(AsyncGetURLsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>> PrepareAsyncGetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>>(PrepareAsyncGetURLsRaw(context, request, cq));
    }
    ::grpc::Status SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::frontier::SubmitResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>> AsyncSubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>>(AsyncSubmitURLsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>> PrepareAsyncSubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>>(PrepareAsyncSubmitURLsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, std::function<void(::grpc::Status)>) override;
      void GetURLs(::grpc::ClientContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitURLs(::grpc::ClientContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>* AsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frontier::URLResponse>* PrepareAsyncGetURLsRaw(::grpc::ClientContext* context, const ::frontier::URLRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>* AsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::frontier::SubmitResponse>* PrepareAsyncSubmitURLsRaw(::grpc::ClientContext* context, const ::frontier::URLBatch& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetURLs_;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitURLs_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetURLs(::grpc::ServerContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response);
    virtual ::grpc::Status SubmitURLs(::grpc::ServerContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetURLs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetURLs(::grpc::ServerContext* context, ::frontier::URLRequest* request, ::grpc::ServerAsyncResponseWriter< ::frontier::URLResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitURLs(::grpc::ServerContext* context, ::frontier::URLBatch* request, ::grpc::ServerAsyncResponseWriter< ::frontier::SubmitResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetURLs<WithAsyncMethod_SubmitURLs<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetURLs() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::frontier::URLRequest, ::frontier::URLResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frontier::URLRequest* request, ::frontier::URLResponse* response) { return this->GetURLs(context, request, response); }));}
    void SetMessageAllocatorFor_GetURLs(
        ::grpc::MessageAllocator< ::frontier::URLRequest, ::frontier::URLResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frontier::URLRequest, ::frontier::URLResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetURLs(
      ::grpc::CallbackServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::frontier::URLBatch, ::frontier::SubmitResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::frontier::URLBatch* request, ::frontier::SubmitResponse* response) { return this->SubmitURLs(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitURLs(
        ::grpc::MessageAllocator< ::frontier::URLBatch, ::frontier::SubmitResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::frontier::URLBatch, ::frontier::SubmitResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitURLs(
      ::grpc::CallbackServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetURLs<WithCallbackMethod_SubmitURLs<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetURLs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetURLs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetURLs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitURLs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetURLs() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetURLs(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetURLs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitURLs(context, request, response); }));
    }
    ~WithRawCallbackMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SubmitURLs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetURLs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frontier::URLRequest, ::frontier::URLResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frontier::URLRequest, ::frontier::URLResponse>* streamer) {
                       return this->StreamedGetURLs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLRequest* /*request*/, ::frontier::URLResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetURLs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frontier::URLRequest,::frontier::URLResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitURLs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitURLs() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::frontier::URLBatch, ::frontier::SubmitResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::frontier::URLBatch, ::frontier::SubmitResponse>* streamer) {
                       return this->StreamedSubmitURLs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitURLs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitURLs(::grpc::ServerContext* /*context*/, const ::frontier::URLBatch* /*request*/, ::frontier::SubmitResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitURLs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::frontier::URLBatch,::frontier::SubmitResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetURLs<WithStreamedUnaryMethod_SubmitURLs<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetURLs<WithStreamedUnaryMethod_SubmitURLs<Service > > StreamedService;
};

}  // namespace frontier


#endif  // GRPC_frontier_2eproto__INCLUDED
