// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frontier.proto

#include "frontier.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace frontier {
PROTOBUF_CONSTEXPR URLRequest::URLRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.node_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.count_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct URLRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR URLRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~URLRequestDefaultTypeInternal() {}
  union {
    URLRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 URLRequestDefaultTypeInternal _URLRequest_default_instance_;
PROTOBUF_CONSTEXPR URLResponse::URLResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.urls_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct URLResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR URLResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~URLResponseDefaultTypeInternal() {}
  union {
    URLResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 URLResponseDefaultTypeInternal _URLResponse_default_instance_;
PROTOBUF_CONSTEXPR URLBatch::URLBatch(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.urls_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct URLBatchDefaultTypeInternal {
  PROTOBUF_CONSTEXPR URLBatchDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~URLBatchDefaultTypeInternal() {}
  union {
    URLBatch _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 URLBatchDefaultTypeInternal _URLBatch_default_instance_;
PROTOBUF_CONSTEXPR SubmitResponse::SubmitResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.accepted_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SubmitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubmitResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubmitResponseDefaultTypeInternal() {}
  union {
    SubmitResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubmitResponseDefaultTypeInternal _SubmitResponse_default_instance_;
}  // namespace frontier
static ::_pb::Metadata file_level_metadata_frontier_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_frontier_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_frontier_2eproto = nullptr;

const uint32_t TableStruct_frontier_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frontier::URLRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::frontier::URLRequest, _impl_.count_),
  PROTOBUF_FIELD_OFFSET(::frontier::URLRequest, _impl_.node_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frontier::URLResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::frontier::URLResponse, _impl_.urls_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frontier::URLBatch, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::frontier::URLBatch, _impl_.urls_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::frontier::SubmitResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::frontier::SubmitResponse, _impl_.accepted_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::frontier::URLRequest)},
  { 8, -1, -1, sizeof(::frontier::URLResponse)},
  { 15, -1, -1, sizeof(::frontier::URLBatch)},
  { 22, -1, -1, sizeof(::frontier::SubmitResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::frontier::_URLRequest_default_instance_._instance,
  &::frontier::_URLResponse_default_instance_._instance,
  &::frontier::_URLBatch_default_instance_._instance,
  &::frontier::_SubmitResponse_default_instance_._instance,
};

const char descriptor_table_protodef_frontier_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016frontier.proto\022\010frontier\",\n\nURLRequest"
  "\022\r\n\005count\030\001 \001(\005\022\017\n\007node_id\030\002 \001(\t\"\033\n\013URLR"
  "esponse\022\014\n\004urls\030\001 \003(\t\"\030\n\010URLBatch\022\014\n\004url"
  "s\030\001 \003(\t\"\"\n\016SubmitResponse\022\020\n\010accepted\030\001 "
  "\001(\0052~\n\010Frontier\0226\n\007GetURLs\022\024.frontier.UR"
  "LRequest\032\025.frontier.URLResponse\022:\n\nSubmi"
  "tURLs\022\022.frontier.URLBatch\032\030.frontier.Sub"
  "mitResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_frontier_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_frontier_2eproto = {
    false, false, 299, descriptor_table_protodef_frontier_2eproto,
    "frontier.proto",
    &descriptor_table_frontier_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_frontier_2eproto::offsets,
    file_level_metadata_frontier_2eproto, file_level_enum_descriptors_frontier_2eproto,
    file_level_service_descriptors_frontier_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_frontier_2eproto_getter() {
  return &descriptor_table_frontier_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_frontier_2eproto(&descriptor_table_frontier_2eproto);
namespace frontier {

// ===================================================================

class URLRequest::_Internal {
 public:
};

URLRequest::URLRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:frontier.URLRequest)
}
URLRequest::URLRequest(const URLRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  URLRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.node_id_){}
    , decltype(_impl_.count_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_id().empty()) {
    _this->_impl_.node_id_.Set(from._internal_node_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.count_ = from._impl_.count_;
  // @@protoc_insertion_point(copy_constructor:frontier.URLRequest)
}

inline void URLRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.node_id_){}
    , decltype(_impl_.count_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

URLRequest::~URLRequest() {
  // @@protoc_insertion_point(destructor:frontier.URLRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void URLRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.node_id_.Destroy();
}

void URLRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void URLRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:frontier.URLRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.node_id_.ClearToEmpty();
  _impl_.count_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* URLRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string node_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "frontier.URLRequest.node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* URLRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frontier.URLRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 count = 1;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_count(), target);
  }

  // string node_id = 2;
  if (!this->_internal_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frontier.URLRequest.node_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frontier.URLRequest)
  return target;
}

size_t URLRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frontier.URLRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string node_id = 2;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // int32 count = 1;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_count());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData URLRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    URLRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*URLRequest::GetClassData() const { return &_class_data_; }


void URLRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<URLRequest*>(&to_msg);
  auto& from = static_cast<const URLRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:frontier.URLRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_node_id().empty()) {
    _this->_internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void URLRequest::CopyFrom(const URLRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frontier.URLRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool URLRequest::IsInitialized() const {
  return true;
}

void URLRequest::InternalSwap(URLRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.node_id_, lhs_arena,
      &other->_impl_.node_id_, rhs_arena
  );
  swap(_impl_.count_, other->_impl_.count_);
}

::PROTOBUF_NAMESPACE_ID::Metadata URLRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_frontier_2eproto_getter, &descriptor_table_frontier_2eproto_once,
      file_level_metadata_frontier_2eproto[0]);
}

// ===================================================================

class URLResponse::_Internal {
 public:
};

URLResponse::URLResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:frontier.URLResponse)
}
URLResponse::URLResponse(const URLResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  URLResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.urls_){from._impl_.urls_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:frontier.URLResponse)
}

inline void URLResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.urls_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

URLResponse::~URLResponse() {
  // @@protoc_insertion_point(destructor:frontier.URLResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void URLResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.urls_.~RepeatedPtrField();
}

void URLResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void URLResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:frontier.URLResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.urls_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* URLResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string urls = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_urls();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "frontier.URLResponse.urls"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* URLResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frontier.URLResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string urls = 1;
  for (int i = 0, n = this->_internal_urls_size(); i < n; i++) {
    const auto& s = this->_internal_urls(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frontier.URLResponse.urls");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frontier.URLResponse)
  return target;
}

size_t URLResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frontier.URLResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string urls = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.urls_.size());
  for (int i = 0, n = _impl_.urls_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.urls_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData URLResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    URLResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*URLResponse::GetClassData() const { return &_class_data_; }


void URLResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<URLResponse*>(&to_msg);
  auto& from = static_cast<const URLResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:frontier.URLResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.urls_.MergeFrom(from._impl_.urls_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void URLResponse::CopyFrom(const URLResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frontier.URLResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool URLResponse::IsInitialized() const {
  return true;
}

void URLResponse::InternalSwap(URLResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.urls_.InternalSwap(&other->_impl_.urls_);
}

::PROTOBUF_NAMESPACE_ID::Metadata URLResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_frontier_2eproto_getter, &descriptor_table_frontier_2eproto_once,
      file_level_metadata_frontier_2eproto[1]);
}

// ===================================================================

class URLBatch::_Internal {
 public:
};

URLBatch::URLBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:frontier.URLBatch)
}
URLBatch::URLBatch(const URLBatch& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  URLBatch* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.urls_){from._impl_.urls_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:frontier.URLBatch)
}

inline void URLBatch::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.urls_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

URLBatch::~URLBatch() {
  // @@protoc_insertion_point(destructor:frontier.URLBatch)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void URLBatch::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.urls_.~RepeatedPtrField();
}

void URLBatch::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void URLBatch::Clear() {
// @@protoc_insertion_point(message_clear_start:frontier.URLBatch)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.urls_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* URLBatch::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string urls = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_urls();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "frontier.URLBatch.urls"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* URLBatch::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frontier.URLBatch)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string urls = 1;
  for (int i = 0, n = this->_internal_urls_size(); i < n; i++) {
    const auto& s = this->_internal_urls(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "frontier.URLBatch.urls");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frontier.URLBatch)
  return target;
}

size_t URLBatch::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frontier.URLBatch)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string urls = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.urls_.size());
  for (int i = 0, n = _impl_.urls_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.urls_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData URLBatch::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    URLBatch::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*URLBatch::GetClassData() const { return &_class_data_; }


void URLBatch::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<URLBatch*>(&to_msg);
  auto& from = static_cast<const URLBatch&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:frontier.URLBatch)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.urls_.MergeFrom(from._impl_.urls_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void URLBatch::CopyFrom(const URLBatch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frontier.URLBatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool URLBatch::IsInitialized() const {
  return true;
}

void URLBatch::InternalSwap(URLBatch* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.urls_.InternalSwap(&other->_impl_.urls_);
}

::PROTOBUF_NAMESPACE_ID::Metadata URLBatch::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_frontier_2eproto_getter, &descriptor_table_frontier_2eproto_once,
      file_level_metadata_frontier_2eproto[2]);
}

// ===================================================================

class SubmitResponse::_Internal {
 public:
};

SubmitResponse::SubmitResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:frontier.SubmitResponse)
}
SubmitResponse::SubmitResponse(const SubmitResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SubmitResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.accepted_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.accepted_ = from._impl_.accepted_;
  // @@protoc_insertion_point(copy_constructor:frontier.SubmitResponse)
}

inline void SubmitResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.accepted_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SubmitResponse::~SubmitResponse() {
  // @@protoc_insertion_point(destructor:frontier.SubmitResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SubmitResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SubmitResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SubmitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:frontier.SubmitResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.accepted_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 accepted = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.accepted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SubmitResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:frontier.SubmitResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 accepted = 1;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_accepted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:frontier.SubmitResponse)
  return target;
}

size_t SubmitResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:frontier.SubmitResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 accepted = 1;
  if (this->_internal_accepted() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_accepted());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SubmitResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SubmitResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SubmitResponse::GetClassData() const { return &_class_data_; }


void SubmitResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SubmitResponse*>(&to_msg);
  auto& from = static_cast<const SubmitResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:frontier.SubmitResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_accepted() != 0) {
    _this->_internal_set_accepted(from._internal_accepted());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SubmitResponse::CopyFrom(const SubmitResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:frontier.SubmitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitResponse::IsInitialized() const {
  return true;
}

void SubmitResponse::InternalSwap(SubmitResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.accepted_, other->_impl_.accepted_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_frontier_2eproto_getter, &descriptor_table_frontier_2eproto_once,
      file_level_metadata_frontier_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace frontier
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::frontier::URLRequest*
Arena::CreateMaybeMessage< ::frontier::URLRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frontier::URLRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::frontier::URLResponse*
Arena::CreateMaybeMessage< ::frontier::URLResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frontier::URLResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::frontier::URLBatch*
Arena::CreateMaybeMessage< ::frontier::URLBatch >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frontier::URLBatch >(arena);
}
template<> PROTOBUF_NOINLINE ::frontier::SubmitResponse*
Arena::CreateMaybeMessage< ::frontier::SubmitResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::frontier::SubmitResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
